name: messages
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.1
  clipboard: ^0.1.3
  get: ^4.6.5
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.6
  path_provider: ^2.0.1
  voice_message_package: ^0.0.74
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.1.14
  cached_network_image: ^3.2.1
  open_file: ^3.2.1
  permission_handler: ^10.0.0
  dio: ^4.0.6
  flutter_audio_recorder2: ^0.0.2
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
     - assets/
